update=Wed Nov  2 15:22:20 2016
version=1
last_client=kicad
[pcbnew]
version=1
LastNetListRead=
UseCmpFile=1
PadDrill=0.600000000000
PadDrillOvalY=0.600000000000
PadSizeH=1.500000000000
PadSizeV=1.500000000000
PcbTextSizeV=1.500000000000
PcbTextSizeH=1.500000000000
PcbTextThickness=0.300000000000
ModuleTextSizeV=1.000000000000
ModuleTextSizeH=1.000000000000
ModuleTextSizeThickness=0.150000000000
SolderMaskClearance=0.000000000000
SolderMaskMinWidth=0.000000000000
DrawSegmentWidth=0.200000000000
BoardOutlineThickness=0.100000000000
ModuleOutlineThickness=0.150000000000
[cvpcb]
version=1
NetIExt=net
[general]
version=1
[eeschema]
version=1
LibDir=
[eeschema/libraries]
LibName1=/home/lchico/Especialidad/Proyecto/Hardware/poncho_fermentacion_vino_tp (copy)/analog-cache
LibName2=/home/lchico/Especialidad/Proyecto/Hardware/poncho_fermentacion_vino_tp (copy)/ciaa-nxp-cache
LibName3=/home/lchico/Especialidad/Proyecto/Hardware/poncho_fermentacion_vino_tp (copy)/ciaa-nxp-rescue
LibName4=/home/lchico/Especialidad/Proyecto/Hardware/poncho_fermentacion_vino_tp (copy)/components/74LVC1G04GW
LibName5=/home/lchico/Especialidad/Proyecto/Hardware/poncho_fermentacion_vino_tp (copy)/components/93CXX
LibName6=/home/lchico/Especialidad/Proyecto/Hardware/poncho_fermentacion_vino_tp (copy)/components/BLM15HG6015N1D
LibName7=/home/lchico/Especialidad/Proyecto/Hardware/poncho_fermentacion_vino_tp (copy)/components/FT2232H
LibName8=/home/lchico/Especialidad/Proyecto/Hardware/poncho_fermentacion_vino_tp (copy)/components/IS42S16400F
LibName9=/home/lchico/Especialidad/Proyecto/Hardware/poncho_fermentacion_vino_tp (copy)/components/LPC4337JBD144
LibName10=/home/lchico/Especialidad/Proyecto/Hardware/poncho_fermentacion_vino_tp (copy)/components/MIC2025
LibName11=/home/lchico/Especialidad/Proyecto/Hardware/poncho_fermentacion_vino_tp (copy)/components/PBSS5240
LibName12=/home/lchico/Especialidad/Proyecto/Hardware/poncho_fermentacion_vino_tp (copy)/components/PRTR5V0U2X
LibName13=/home/lchico/Especialidad/Proyecto/Hardware/poncho_fermentacion_vino_tp (copy)/components/PS2805
LibName14=/home/lchico/Especialidad/Proyecto/Hardware/poncho_fermentacion_vino_tp (copy)/components/SCHA5B0200
LibName15=/home/lchico/Especialidad/Proyecto/Hardware/poncho_fermentacion_vino_tp (copy)/components/Si50x
LibName16=/home/lchico/Especialidad/Proyecto/Hardware/poncho_fermentacion_vino_tp (copy)/components/TJA1040
LibName17=/home/lchico/Especialidad/Proyecto/Hardware/poncho_fermentacion_vino_tp (copy)/components/TXB0108
LibName18=/home/lchico/Especialidad/Proyecto/Hardware/poncho_fermentacion_vino_tp (copy)/components/Transil_diode
LibName19=/home/lchico/Especialidad/Proyecto/Hardware/poncho_fermentacion_vino_tp (copy)/components/amesser-ad
LibName20=/home/lchico/Especialidad/Proyecto/Hardware/poncho_fermentacion_vino_tp (copy)/components/amesser-cmos4000
LibName21=/home/lchico/Especialidad/Proyecto/Hardware/poncho_fermentacion_vino_tp (copy)/components/amesser-conn
LibName22=/home/lchico/Especialidad/Proyecto/Hardware/poncho_fermentacion_vino_tp (copy)/components/amesser-discrete
LibName23=/home/lchico/Especialidad/Proyecto/Hardware/poncho_fermentacion_vino_tp (copy)/components/amesser-linear
LibName24=/home/lchico/Especialidad/Proyecto/Hardware/poncho_fermentacion_vino_tp (copy)/components/amesser-power
LibName25=/home/lchico/Especialidad/Proyecto/Hardware/poncho_fermentacion_vino_tp (copy)/components/amesser-usb
LibName26=/home/lchico/Especialidad/Proyecto/Hardware/poncho_fermentacion_vino_tp (copy)/components/audio-vlsi
LibName27=/home/lchico/Especialidad/Proyecto/Hardware/poncho_fermentacion_vino_tp (copy)/components/bat54_c
LibName28=/home/lchico/Especialidad/Proyecto/Hardware/poncho_fermentacion_vino_tp (copy)/components/capteurs
LibName29=/home/lchico/Especialidad/Proyecto/Hardware/poncho_fermentacion_vino_tp (copy)/components/fqt13n06l
LibName30=/home/lchico/Especialidad/Proyecto/Hardware/poncho_fermentacion_vino_tp (copy)/components/g5v2
LibName31=/home/lchico/Especialidad/Proyecto/Hardware/poncho_fermentacion_vino_tp (copy)/components/lm2596
LibName32=/home/lchico/Especialidad/Proyecto/Hardware/poncho_fermentacion_vino_tp (copy)/components/mcp1415
LibName33=/home/lchico/Especialidad/Proyecto/Hardware/poncho_fermentacion_vino_tp (copy)/components/mcp1416
LibName34=/home/lchico/Especialidad/Proyecto/Hardware/poncho_fermentacion_vino_tp (copy)/components/mcu-nxp
LibName35=/home/lchico/Especialidad/Proyecto/Hardware/poncho_fermentacion_vino_tp (copy)/components/mcu-st
LibName36=/home/lchico/Especialidad/Proyecto/Hardware/poncho_fermentacion_vino_tp (copy)/components/my_lab
LibName37=/home/lchico/Especialidad/Proyecto/Hardware/poncho_fermentacion_vino_tp (copy)/components/net-phy
LibName38=/home/lchico/Especialidad/Proyecto/Hardware/poncho_fermentacion_vino_tp (copy)/components/nsi50010yt1g
LibName39=/home/lchico/Especialidad/Proyecto/Hardware/poncho_fermentacion_vino_tp (copy)/components/pbss5240xf
LibName40=/home/lchico/Especialidad/Proyecto/Hardware/poncho_fermentacion_vino_tp (copy)/components/regulators
LibName41=/home/lchico/Especialidad/Proyecto/Hardware/poncho_fermentacion_vino_tp (copy)/components/rs485_rs232_can
LibName42=/home/lchico/Especialidad/Proyecto/Hardware/poncho_fermentacion_vino_tp (copy)/components/s25fl032p0xmfi013
LibName43=/home/lchico/Especialidad/Proyecto/Hardware/poncho_fermentacion_vino_tp (copy)/components/sensors
LibName44=/home/lchico/Especialidad/Proyecto/Hardware/poncho_fermentacion_vino_tp (copy)/components/sw_push
LibName45=/home/lchico/Especialidad/Proyecto/Hardware/poncho_fermentacion_vino_tp (copy)/components/tvs
LibName46=/home/lchico/Especialidad/Proyecto/Hardware/poncho_fermentacion_vino_tp (copy)/components/w_device
LibName47=power
LibName48=device
LibName49=transistors
LibName50=conn
LibName51=linear
LibName52=regul
LibName53=74xx
LibName54=cmos4000
LibName55=adc-dac
LibName56=memory
LibName57=xilinx
LibName58=microcontrollers
LibName59=dsp
LibName60=microchip
LibName61=analog_switches
LibName62=motorola
LibName63=texas
LibName64=intel
LibName65=audio
LibName66=interface
LibName67=digital-audio
LibName68=philips
LibName69=display
LibName70=cypress
LibName71=siliconi
LibName72=opto
LibName73=atmel
LibName74=contrib
LibName75=valves
